# Starship configuration for the Nord color theme

# Schema for validation
"$schema" = 'https://starship.rs/config-schema.json'

# Define the overall prompt format for the left side
format = """
[](color_frost_blue)\
$os\
$username\
[](bg:color_snow_storm_light fg:color_frost_blue)\
$directory\
[](fg:color_snow_storm_light bg:color_frost_green_aqua)\
$git_branch\
$git_status\
[](fg:color_frost_green_aqua bg:color_polar_night_darker)\
$docker_context\
$conda\
$pixi\
$aws\
$gcloud\
[](fg:color_polar_night_darker bg:color_polar_night_darkest)""" # Spiked end for the left prompt, transitioning to the right's background

# Define the right-aligned prompt format. Modules themselves will handle the box styling.
right_format = """
[](fg:color_frost_green_aqua)
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:color_snow_storm_light bg:color_frost_green_aqua)
$cmd_duration\
[](fg:color_frost_blue bg:color_snow_storm_light)
$character
[](fg:color_frost_blue)
"""

# Define the custom Nord color palette
palette = 'nord'

[palettes.nord]
# Polar Night (dark)
color_polar_night_darkest = '#2e3440'
color_polar_night_darker = '#3b4252'
color_polar_night_medium = '#434c5e'
color_polar_night_light = '#4c566a'

# Snow Storm
color_snow_storm_light = '#d8dee9'
color_snow_storm_medium = '#e5e9f0'
color_storm_snow_dark = '#eceff4'

# Frost (blueish)
color_frost_green_aqua = '#8fbcbb'
color_frost_light_blue = '#88c0d0'
color_frost_blue = '#81a1c1'
color_frost_dark_blue = '#5e81ac'

# Aurora accent colors
color_aurora_red = '#bf616a'
color_aurora_orange = '#d08770'
color_aurora_yellow = '#ebcb8b'
color_aurora_green = '#a3be8c'
color_aurora_purple = '#b48ead'

# Module Configurations

[os]
disabled = false
style = "bg:color_frost_blue fg:color_snow_storm_light" # Using a frosty blue background for OS

[os.symbols]
NixOS = " "

[username]
show_always = false
style_user = "bg:color_frost_blue fg:color_snow_storm_light"
style_root = "bg:color_aurora_red fg:color_snow_storm_light" # Red for root for immediate visibility
format = '[ $user ]($style)'

[directory]
style = "fg:color_polar_night_darkest bg:color_snow_storm_light" # Dark text on light background
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_frost_green_aqua" # Using a greenish-aqua for git branch
format = '[[ $symbol $branch ](fg:color_polar_night_darkest bg:color_frost_green_aqua)]($style)'

[git_status]
style = "bg:color_frost_green_aqua"
format = '[[($all_status$ahead_behind )](fg:color_polar_night_darkest bg:color_frost_green_aqua)]($style)'
untracked = '?${count} '   # Untracked files
stashed = '$${count} '     # Stashed changes
modified = '!${count} '    # Modified files
staged = '+${count} '      # Staged files
renamed = '»${count} '     # Renamed files
deleted = '✘${count} '     # Deleted files
conflicted = '=${count} '   # Conflicted files
ahead = '⇡${count} '       # Ahead of remote
behind = '⇣${count} '      # Behind remote
diverged = '⇕⇡${ahead_count} ⇣${behind_count} ' # Diverged from remote

[nodejs]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version)]($style)"

[c]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[cpp]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[rust]
symbol = "󱘗 "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[golang]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[php]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[java]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[kotlin]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[haskell]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[python]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[elixir]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[elm]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[nim]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[scala]
symbol = " "
style = "bg:color_frost_green_aqua fg:color_polar_night_darkest"
format = "[$symbol($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:color_polar_night_darker fg:color_snow_storm_light"
format = "[$symbol( $context) ]($style)"

[conda]
symbol = " "
style = "bg:color_polar_night_darker fg:color_snow_storm_light"
format = "[$symbol( $environment)]($style)"

[pixi]
symbol = "󰏗 "
style = "bg:color_polar_night_darker fg:color_snow_storm_light"
format = "[$symbol( $version)( $environment)]($style)"

[aws]
symbol = " "
style = "bg:color_polar_night_darker fg:color_snow_storm_light"
format = "[$symbol( $profile)]($style)"

[gcloud]
symbol = " "
style = "bg:color_polar_night_darker fg:color_snow_storm_light"
format = "[$symbol( $project)]($style)"

[cmd_duration]
min_time = 500
format = '[$duration ](bg:color_snow_storm_light fg:color_polar_night_darkest)'

[character]
format = '$symbol'
success_symbol = '[✔](bold color_polar_night_darkest bg:color_frost_blue)'
error_symbol = '[✖](bold color_polar_night_darkest bg:color_frost_blue)'

